## Output path is defined here
artifacts_root: Artifacts/data_ingestion

## Data Ingestion
data_ingestion:
  root_dir: Artifacts/data_ingestion
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
  local_data_file: Artifacts/data_ingestion/data_zip/data.zip
  unzip_dir: Artifacts/data_ingestion/data_unzip

## Data Transformation
data_transformation:
  root_dir: Artifacts/data_transformation
  data_path: Artifacts/data_ingestion/data_unzip/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

## Model Trainer
model_trainer:
  root_dir: Artifacts/model_trainer
  data_path: Artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

## Model Evaluation
model_evaluation:
  root_dir: Artifacts/model_evaluation
  data_path: Artifacts/data_transformation/samsum_dataset
  model_path: Artifacts/model_trainer/pagasus-samsum-model
  tokenizer_path: Artifacts/model_trainer/tokenizer
  metric_filename: Artifacts/model_evaluation/metric.csv
